
obj-m += aml.o aml_fe_avl62x1_av201x.o aml_fe_avl68x2_r848.o r848a.o

aml-objs=aml_dvb.o aml_dmx.o

#EXTRA_CFLAGS += -D_AVL_LINUX_DVB_
EXTRA_CFLAGS += -I. 
EXTRA_CFLAGS += -Idrivers/media/dvb-core -Idrivers/media/usb/dvb-usb -Idrivers/media/dvb-frontends -Idrivers/media/tuners 
#EXTRA_CFLAGS += -Idrivers/amlogic/dvb-avl -Idrivers/amlogic/dvb-avl/sdk_src -Idrivers/amlogic/dvb-avl/AV201X

obj-m += dvb-frontends-availink/availink/


